services:

  redis:
    image: redis:latest
    container_name: wallet_redis
    restart: always
    ports:
      - "6386:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10


  postgres:
    image: postgres:15
    container_name: wallet_postgres
    restart: always
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet123
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wallet", "-d", "walletdb"]
      interval: 5s
      timeout: 5s
      retries: 10


  adminer:
    image: adminer
    container_name: wallet_adminer
    ports:
      - "8090:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB: walletdb
    depends_on:
      postgres:
        condition: service_healthy

  wallet-service:
    build: .
    container_name: wallet_backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletdb
      SPRING_DATASOURCE_USERNAME: wallet
      SPRING_DATASOURCE_PASSWORD: wallet123
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
      WALLET_IDEMPOTENCY_REDIS_ENABLED: "true"
    restart: always

volumes:
  postgres_data:
  redis_data: